# Created this service to access kafka from the cluster
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - port: 9092
    targetPort: 9092

---

kind: Endpoints
apiVersion: v1
metadata:
  name: kafka-service
subsets:
  - addresses:
      - ip: "192.168.49.1"
    ports:
      - port: 9092